version: '3'
services:
  backend:
    image: money_transfer_back:latest
    ports:
      - '5500:5500'
    build: .
  frontend:
    image: card_transfer_front:latest
    ports:
      - '3000:3000'
    depends_on:
      - backend
    build: ./webapp